version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_java_prime
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-java_prime}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dev}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
