spring:
  application:
    name: DesafioJavaPrime

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:java_prime}
    username: ${MYSQL_USER:dev}
    password: ${MYSQL_PASSWORD:dev}
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /java_prime

external:
  credit-score:
    base-url: http://localhost:9090